on:
  workflow_call:
  workflow_dispatch:
  push:
    paths:
      - 'chart/**'
    branches: [ main ]

jobs:
  deploy_universal:
    uses: flmorg/universal-workflows/.github/workflows/chart.install.yml@main
    with:
      githubContext: ${{ toJSON(github) }}
      chartRepo: oci://ghcr.io/flmorg
      chartName: universal-chart
      version: ^1.0.0
      valuesPath: chart/values.yaml
      releaseName: main
    secrets: inherit